cmake_minimum_required(VERSION 3.24)

if(NOT DEFINED CONFIG_FILE OR CONFIG_FILE STREQUAL "")
  message(FATAL_ERROR "CONFIG_FILE is required")
endif()

if(NOT EXISTS "${CONFIG_FILE}")
  message(FATAL_ERROR "BusyBox config file does not exist: ${CONFIG_FILE}")
endif()

if(NOT DEFINED FRAGMENT_FILE OR FRAGMENT_FILE STREQUAL "" OR NOT EXISTS "${FRAGMENT_FILE}")
  message(STATUS "No BusyBox config fragment applied")
  return()
endif()

file(READ "${CONFIG_FILE}" _config_text)
file(READ "${FRAGMENT_FILE}" _fragment_text)

string(REPLACE "\r\n" "\n" _config_text "${_config_text}")
string(REPLACE "\r\n" "\n" _fragment_text "${_fragment_text}")

string(REPLACE "\n" ";" _config_lines "${_config_text}")
string(REPLACE "\n" ";" _fragment_lines "${_fragment_text}")

set(_fragment_keys "")
set(_normalized_fragment_lines "")

function(stage0_append_config_override input_line)
  if("${input_line}" STREQUAL "")
    return()
  endif()
  if(input_line MATCHES "^# ([A-Za-z0-9_]+) is not set$")
    list(APPEND _fragment_keys "${CMAKE_MATCH_1}")
    list(APPEND _normalized_fragment_lines "${input_line}")
  elseif(input_line MATCHES "^([A-Za-z0-9_]+)=.*$")
    list(APPEND _fragment_keys "${CMAKE_MATCH_1}")
    list(APPEND _normalized_fragment_lines "${input_line}")
  endif()
  set(_fragment_keys "${_fragment_keys}" PARENT_SCOPE)
  set(_normalized_fragment_lines "${_normalized_fragment_lines}" PARENT_SCOPE)
endfunction()

foreach(_line IN LISTS _fragment_lines)
  string(STRIP "${_line}" _line)
  if(_line STREQUAL "")
    continue()
  endif()
  stage0_append_config_override("${_line}")
endforeach()

if(DEFINED OVERRIDE_CROSS_COMPILER_PREFIX AND NOT OVERRIDE_CROSS_COMPILER_PREFIX STREQUAL "")
  stage0_append_config_override("CONFIG_CROSS_COMPILER_PREFIX=\"${OVERRIDE_CROSS_COMPILER_PREFIX}\"")
endif()

if(DEFINED OVERRIDE_SYSROOT AND NOT OVERRIDE_SYSROOT STREQUAL "")
  stage0_append_config_override("CONFIG_SYSROOT=\"${OVERRIDE_SYSROOT}\"")
endif()

set(_merged_lines "")
foreach(_line IN LISTS _config_lines)
  set(_skip_line FALSE)
  foreach(_key IN LISTS _fragment_keys)
    if(_line MATCHES "^${_key}=.*$" OR _line STREQUAL "# ${_key} is not set")
      set(_skip_line TRUE)
      break()
    endif()
  endforeach()
  if(NOT _skip_line)
    list(APPEND _merged_lines "${_line}")
  endif()
endforeach()

list(APPEND _merged_lines "" "# stage0 overrides")
list(APPEND _merged_lines ${_normalized_fragment_lines})

string(JOIN "\n" _merged_text ${_merged_lines})
file(WRITE "${CONFIG_FILE}" "${_merged_text}\n")
